---
all:
  children:
    oracle_rac:
      children:
        oracle_rac_node1:
          hosts:
            oracle-node01.lab.dev.example.com:
              ansible_host: 172.25.250.67
              node_id: 1
              public_ip: 172.25.250.67
              private_ip: 192.168.10.67
              vip_ip: 172.25.250.72
              vip_hostname: oracle-node01-vip.lab.dev.example.com
        oracle_rac_node2:
          hosts:
            oracle-node02.lab.dev.example.com:
              ansible_host: 172.25.250.68
              node_id: 2
              public_ip: 172.25.250.68
              private_ip: 192.168.10.68
              vip_ip: 172.25.250.73
              vip_hostname: oracle-node02-vip.lab.dev.example.com
  vars:
    ansible_user: root
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    domain_name: lab.dev.example.com 
