---
all:
  children:
    oracle_rac:
      children:
        oracle_rac_node1:
          hosts:
            oracle-node01.lab.dev.example.com:
              ansible_host: 192.168.2.130
              node_id: 1
              public_ip: 192.168.2.130
              private_ip: 172.25.250.130
              vip_ip: 192.168.2.132
              vip_hostname: oracle-node01-vip.lab.dev.example.com
        oracle_rac_node2:
          hosts:
            oracle-node02.lab.dev.example.com:
              ansible_host: 192.168.2.131
              node_id: 2
              public_ip: 192.168.2.131
              private_ip: 172.25.250.131
              vip_ip: 192.168.2.133
              vip_hostname: oracle-node02-vip.lab.dev.example.com
  vars:
    ansible_user: root
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    domain_name: lab.dev.example.com 